// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api here',
    appId: '1:50861521977:web:06f30ac50889182da5e1e8',
    messagingSenderId: '50861521977',
    projectId: 'aab-e-pak-app',
    authDomain: 'aab-e-pak-app.firebaseapp.com',
    storageBucket: 'aab-e-pak-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api here',
    appId: '1:50861521977:android:8c2a796a958dc40ca5e1e8',
    messagingSenderId: '50861521977',
    projectId: 'aab-e-pak-app',
    storageBucket: 'aab-e-pak-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your api here',
    appId: '1:50861521977:ios:c1a8288bcb9581caa5e1e8',
    messagingSenderId: '50861521977',
    projectId: 'aab-e-pak-app',
    storageBucket: 'aab-e-pak-app.firebasestorage.app',
    iosBundleId: 'com.example.aabEPak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your api here',
    appId: '1:50861521977:ios:c1a8288bcb9581caa5e1e8',
    messagingSenderId: '50861521977',
    projectId: 'aab-e-pak-app',
    storageBucket: 'aab-e-pak-app.firebasestorage.app',
    iosBundleId: 'com.example.aabEPak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your api here',
    appId: '1:50861521977:web:34e3db93686e333aa5e1e8',
    messagingSenderId: '50861521977',
    projectId: 'aab-e-pak-app',
    authDomain: 'aab-e-pak-app.firebaseapp.com',
    storageBucket: 'aab-e-pak-app.firebasestorage.app',
  );
}
